services:
  mosquitto-central:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-central
    ports:
      - "1884:1883"
    volumes:
      - ./conf:/mosquitto/config:Z
      - ./mosquitto-central/data:/mosquitto/data:Z
      - ./mosquitto-central/log:/mosquitto/log:Z
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "mosquitto_pub -h localhost -p 1883 -t healthcheck -m ping || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "kafka:9092"]
      interval: 5s
      retries: 20


  kafka-connect:
    build: ./connect
    container_name: kafka-connect
    depends_on:
      kafka:
        condition: service_healthy
      mosquitto-central:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_PLUGIN_PATH: /usr/share/java
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/connectors"]
      interval: 5s
      timeout: 5s
      retries: 20

  connector-init:
    image: curlimages/curl:latest
    container_name: connector-init
    depends_on:
      kafka-connect:
        condition: service_healthy
    volumes:
      - ./conf/connectors:/connectors:Z
    entrypoint: >
      sh -c '
      echo "Registering connectors...";
      for f in /connectors/*.json; do
        name=$(basename "$$f" .json)
        echo "Creating connector $$name..."
        curl -s -X POST -H "Content-Type: application/json" --data @"$$f" http://kafka-connect:8083/connectors || true
      done;
      echo "Done.";
      '

  kafdrop: 
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092