services:
  mosquitto-central:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-central
    ports:
      - "1884:1883"
    volumes:
      - ./conf:/mosquitto/config:Z
      - ./mosquitto-central/data:/mosquitto/data:Z
      - ./mosquitto-central/log:/mosquitto/log:Z
    restart: unless-stopped